targets::tar_option_set(packages = c("SpeciesPoolR", "data.table")#, 
    #controller = crew::crew_controller_local(workers = 6), error = "null"
    )
list(targets::tar_target(file, command = "EllembergTable.xlsx", format = "file"), 
    targets::tar_target(data, get_data(file, filter = NULL)), 
    targets::tar_target(shp, command = NULL, format = "file"), 
    targets::tar_target(Raster, command = "Dir/LU.tif", format = "file"), 
    targets::tar_target(Landusesuitability, "NewHabSut.tif", 
        format = "file"), targets::tar_target(Clean, SpeciesPoolR::Clean_Taxa(data$Species)), 
    targets::tar_target(Count_Presences, count_presences(Clean, 
        country = "DK", shapefile = shp), pattern = map(Clean)), 
    targets::tar_target(More_than_zero, Count_Presences[N > 0, 
        , by = species, sum(N)]), targets::tar_target(Presences, 
        get_presences(More_than_zero$species, country = "DK", 
            shapefile = shp, limit = 10000), pattern = map(More_than_zero)), 
    targets::tar_target(buffer, make_buffer_rasterized(DT = Presences, 
        file = Raster, dist = 500), pattern = map(Presences)),
    targets::tar_target(LookUpFile, command = "Lookup.csv", format = "file"),
    targets::tar_target(LookUpTable, 
        data.table::fread(LookUpFile)), 
    targets::tar_target(Long_LU_table, generate_long_landuse_table(path = Landusesuitability)), 
    targets::tar_target(Final_Presences, make_final_presences(Long_LU_table, 
        buffer, LookUpTable)), targets::tar_target(unique_species, 
        unique(Final_Presences$species)), targets::tar_target(unique_habitats, 
        unique(Final_Presences$Landuse)), targets::tar_target(export_presences, 
        export_final_presences(Final_Presences[species == unique_species, 
            ], folder = "Field_Final_Presences"), pattern = map(unique_species), 
        format = "file"), targets::tar_target(Phylo_Tree, generate_tree(More_than_zero)), 
    targets::tar_target(rarity_weight, calc_rarity_weight(More_than_zero)), 
    targets::tar_target(rarity, calc_rarity(Final_Presences[Landuse == 
        unique_habitats, ], rarity_weight), pattern = map(unique_habitats)),
    targets::tar_target(PhyloDiversity, calc_pd(Final_Presences[Landuse == 
                                                                  unique_habitats, ], Phylo_Tree), pattern = map(unique_habitats)),
    targets::tar_target(name = output_Rarity, command = export_rarity(Results = rarity, 
                                                                      path = Raster), map(rarity), format = "file"), targets::tar_target(name = output_Richness, 
                                                                                                                                         command = export_richness(Results = PhyloDiversity, path = Raster), 
                                                                                                                                         map(PhyloDiversity), format = "file"), targets::tar_target(name = output_PD, 
                                                                                                                                                                                                    command = export_pd(Results = PhyloDiversity, path = Raster), 
                                                                                                                                                                                                    map(PhyloDiversity), format = "file"))
